import Foundation

class Video {
    
    var title: String!
    var description: String!
    var id: String!
    
}




func buildVideos() -> [Video] {
    var videos = [Video]()
    
    
    let videoOne = Video()
    videoOne.title = "JOSS STONE – ‘THE HIGH ROAD'"
    videoOne.description = "The Brief \n\nWe were commissioned by US record companies Stone’d records and S curve to provide the post production and VFX for Joss Stone’s music video ‘The High Road’. We had an extremely quick turn around of eight days. The video had been shot by an LA based company during the daytime and they had used heavy amounts of smoke and ran into problems with post production and VFX . The management, labels and artist wanted the video to be at night and for us to composite an array of VFX and 3D animation into the video. We were therefore commissioned to take over from the LA production company. \n\nThe Process \n\nOur in house team of 3D/VFX artists and editors worked laboriously throughout the post production stages. We completed an array of post production and VFX/animation techniques including, Rotoscoping, VFX work, animation (2D/3D) lighting, grading and skin enhancements. \n\nThe Result \n\nThe video to date has had over a million hits and has lead to further commissions by Stone’d records and S curve. Joss Stone stated ‘Lovelove Films have done an amazing job’."
    videoOne.id = "CfFgoBzKXIk"
    videos.append(videoOne)
    
    
    let videoTwo = Video()
    videoTwo.title = "JOSS STONE – THE LOVE WE HAD"
    videoTwo.description = "The Brief \n\nAfter successfully completing two projects for Stone’d Records, LoveLove Films were contacted with the opportunity to create a music video from concept to completion for the record label’s prime artist Joss Stone. The label came to us with the most popular track on her latest album The Love We Had, wanting us to complete the video in time to coincide with the song’s worldwide release as a single. \n\nThe Process \n\nLoveLove’s in house writers came up with a concept that perfectly suited the emotionally powerful and heart wrenching song, with the idea of interior rain representing the singer’s emotional state, which physically manifests itself inside her home, destroying all of her personal possessions. LoveLove then spent time constructing the devices that would be needed to bring the video’s concept to life. The rain machine was made by the visual effects team out of store bought items. Location recce’s were conducted to find the perfect apartment to suit the video. LoveLove Films then shot the majority of the music video over two days, filming all of Joss’ footage and everything in the apartment over this period. Finally practical special effects footage was filmed at a separate location, which was able to be made indistinguishable from the apartment setting. As well as the music video LoveLove produced a behind the scenes video, a series of videos for the products featured in the official music video and a lyric music video for The Love We Had.\n\nThe Result \n\nThe video has been a huge success. It has been described by many people as the best music video that Joss Stone has ever made. It has also received huge critical praise from publications such as The Telegraph, The Daily Mail, OK Magazine, The Sun, Promo News and many others. The video has also yielded a high number of viewers, gaining over 500,000 views within three weeks of being uploaded onto Vevo and Youtube. The music video currently has over 4.5 Million views on VEVO. It has also been screened on television channels around the world. In the UK alone it is being shown on the music channels MTV, MTV Music, VH1 and others."
    videoTwo.id = "RRyk8rEQFOY"
    videos.append(videoTwo)
    
    
    let videoThree = Video()
    videoThree.title = "THE MAGIC POTTIES"
    videoThree.description = "The Brief \n\nLovelove Films were approached by Amanda Jenner, Managing Director of both My Carry Potty and the Potty Training Academy, to produce an educational animation for children and parents on Potty training. “The Magic Potties”, is an informative and educational animated film and DVD, complete with extra features, such as a potty training quiz. Amanda is widely known as the UK’s foremost potty training expert and is a Huggies Training ambassador. Since inventing My Carry Potty over 15 years ago and launching into stores worldwide 5 years ago, Amanda has also written a book and is always looking for further inventive ways of teaching important developmental lessons to children. \n\nThe Process \n\nThe film is the culmination of Amanda and LoveLove Films team members working together to create an inventive and original story that would appeal to a wide range of young children who need to embark upon potty training. ‘The Magic Potties’ project has allowed our team of animators to delve into a new animation style and gave them a taste of animating content for children. Adapting Amanda’s book ‘George & Holly and the Magic Potties’ characters into a 15 minute animation with new and exciting scenes for the younger viewer including scenes in space, the beach and exciting flights on bumblebees! \n\nThe Result \n\nThe film is the culmination of Amanda and LoveLove Films team members working together to create an inventive and original story that would appeal to a wide range of young children who need to embark upon potty training. ‘The Magic Potties’ project has allowed our team of animators to delve into a new animation style and gave them a taste of animating content for children. Adapting Amanda’s book ‘George & Holly and the Magic Potties’ characters into a 15 minute animation with new and exciting scenes for the younger viewer including scenes in space, the beach and exciting flights on bumblebees!"
    videoThree.id = "NOYtDOZ3_kk"
    videos.append(videoThree)
    
    let videoFour = Video()
    videoFour.title = "LINSAR"
    videoFour.description = "The Brief \n\nLoveLove Films have continued their relationship with Linsar, which previously saw the creation of Loveloves’ Linsar film at the Euronics Showcase. Linsar needed help to produce a product demonstration video, which would throw their new Linsar product range into the world. The product demo needed to highlight the key benefits of their televisions including Smart TV, Freeview HD, Full HD 1080p, USB Pause/Record and their free five year guarantee. They also needed to increase brand awareness as well as promote their latest products; we needed to ensure that all of this was reflected in the product demonstration video. \n\nThe Process \n\nThe LoveLove Films team hosted a shoot for our client Linsar in our studio space. Barry and Terry enjoyed their time in front of camera as they were interviewed about their brand, revealing its history and ethos. Additional, we used the latest in 3D animation technology to put together several engaging videos. Additionally, using animation combined with live action has allowed Linsar to have videos that are unique and also have that modern, innovative and cutting-edge quality to them. \n\nThe Result \n\nThe LoveLove Films team hosted a shoot for our client Linsar in our studio space. Barry and Terry enjoyed their time in front of camera as they were interviewed about their brand, revealing its history and ethos. Additional, we used the latest in 3D animation technology to put together several engaging videos. Additionally, using animation combined with live action has allowed Linsar to have videos that are unique and also have that modern, innovative and cutting-edge quality to them."
    videoFour.id = "sQDN4cSKD2k"
    videos.append(videoFour)
    
    let videoFive = Video()
    videoFive.title = "TASTE THE PASSION"
    videoFive.description =  "The Brief \n\nAn early project; LoveLove Films decided to enter the “King of Ads” competition ran by Pepsico for the crisp company Doritos, that tasked production companies to make an advert for their crisps; the winner of which would have their video selected as their next television advert. \n\nThe Process \n\nAn early project; LoveLove Films decided to enter the “King of Ads” competition ran by Pepsico for the crisp company Doritos, that tasked production companies to make an advert for their crisps; the winner of which would have their video selected as their next television advert. \n\nThe Result \n\nThe thirty second advert is brilliant in its simplicity, and advertises the project in a familiar, but also unique and visually arresting way. The judges agreed, and the advert went on to become shortlisted into the final fifteen entries, beating thousands of other entries into the competition."
    videoFive.id = "uVANCRZhdQA"
    videos.append(videoFive)
    
    
    let videoSix = Video()
    videoSix.title = "BESPOKE"
    videoSix.description = "TLoveLove were commissioned by Barclaycard to create an advert for their Bespoke Offers app. The client needed something that would both show its ease of use and that it is a luxury convenience app. We created an advert that incorporated animated graphics around a live action rendition of the app being used. The finished video promotes to the audience how they can easily access offers in a concise and appealing manner."
    videoSix.id = "Zw7LjDKqnio"
    videos.append(videoSix)
    
    let videoSeven = Video()
    videoSeven.title = "TOUCH SURGERY"
    videoSeven.description = "The Brief \n\nTouch Surgery was in need of online video content to highlight the innovations of their app, a surgical education tool for doctors and surgeons that teaches by Cognitive Task Simulation. \n\nThe Process \n\nWorking alongside our good friends digital web agency This is Crowd who built the Touch Surgery website. LoveLove films used animation and HD video to complete the project. \n\nThe Result \n\nThe video will act as a dynamic tool to highlight and showcase the innovation of Touch Surgery’s app and approach to teaching. Touch Surgery will use these videos as demonstration aids at presentations and events, embedded on their website and distribute them via social media platforms."
    videoSeven.id = "Y_SAXP6Vf08"
    videos.append(videoSeven)
    
    
    let videoEight = Video()
    videoEight.title = "TEAMJOBS"
    videoEight.description = "The Brief \n\nDorset based Recruitment Company TeamJobs came to LoveLove Films wanting a new video that would revitalise their image, bring their services to a wider audience, and show that they were in fact the “agency with personality.” \n\nThe Process \n\nLoveLove Films created an animated film that showcased the TeamJobs brand and the areas that they specialise in in a unique and engaging fashion. Characters were created of all of the TeamJobs staff members, and a competition was run for their customers to appear in the film. The video was created using a unique form of 2D and 3D animation that highlights the company in a vibrant fashion. \n\nThe Result \n\nLoveLove Films created an animated film that showcased the TeamJobs brand and the areas that they specialise in in a unique and engaging fashion. Characters were created of all of the TeamJobs staff members, and a competition was run for their customers to appear in the film. The video was created using a unique form of 2D and 3D animation that highlights the company in a vibrant fashion."
    videoEight.id = "GhEYNzeqoDE"
    videos.append(videoEight)
    
    let videoNine = Video()
    videoNine.title = "VISIT DORSET FALL IN LOVE WITH DORSET"
    videoNine.description = "The Brief \n\nVisit Dorset commissioned LoveLove Films to create a video that would showcase the diversity and range of activities that can be undertaken in Dorset in a completely unique way. We suggested using parallax animation of photographs to give the video a fresh and innovative visual appeal. \n\nThe Process \n\nLoveLove Films photographed a wide variety of locations across Dorset and were given some of the best photographs ever taken across the county. The LoveLove Films animation team then spent several weeks working on the photographs, transforming them from stills into short animations that would capture the activities onscreen. \n\nThe Result \n\nThe video was posted online, where it gained a very positive reception. On Facebook it received over 30,000 views within 24 hours of being uploaded and more than 400 likes, 750 shares and a wide range of positive comments."
    videoNine.id = "W29u18eKBiE"
    videos.append(videoNine)
    
    let videoTen = Video()
    videoTen.title = "GABBY YOUNG & OTHER ANIMALS – I’VE IMPROVED"
    videoTen.description = "The Brief \n\nLoveLove were approached by Gabby Young & the Other Animals to produce a second music video for the band. Their first single ‘I’ve Improved’ is to be released off of their upcoming album ‘One foot in front of the other’. LoveLove were contracted to produce the music video from concept to completion. \n\nThe Process \n\nLoveLove worked with our in-house writers and designers to conceptualise the track working on narrative structure and storyline. We wanted to create an epic adventure video. We conceptualised an animated world and shot Gabby Young and her band members performing live in front of a green screen and then composited their bodies into the animated realm. This process gave the band a unique eye catching music video which kept in theme with the bands’ other promotional materials – album cover, website etc. \n\nThe Result \n\nGabby Young & the Other Animals unveiled the animated video at their concert in London, it has since gone on to garner over 10,000 views on YouTube alone. The music video along with a live performance by Gabby Young & the Other Animals was showcased at the SXSW 2014 Festival in Austin, Texas. Culturefly featured the music video for ‘I’ve Improved’ as their MVOTW spot on their website and can be quoted: ‘A most unusual video – just like a pop-up book – it’s a creative treat which throws the band into a paper-made landscape of rolling waves and weaving cog-wheels'."
    videoTen.id = "m8ny-8rgN9Y"
    videos.append(videoTen)
    
    let videoEleven = Video()
    videoEleven.title = "GABBY YOUNG & OTHER ARTISTS – ‘IN YOUR HEAD’"
    videoEleven.description = "The Brief \n\nWe were commissioned to produce a music video for artist Gabby Young & Other Animals. We had a completely open brief to create a music video for the track ‘In Your Head’. \n\nThe Process \n\nThe video is made entirely out of photos that we shot in house that have been stylistically animated. We consulted with the band and management on brand ideologies. We created an animated 2D journey where Gabby and fellow band members defeat the Evil Ring Master to rescue animals from a Victorian styled circus.\nThe video was relatively low budget, therefore, we engaged with the artist to raise funds through crowd sourcing. LoveLove came up with the idea that Gabby Young & the Other Animals’ fans could fund the video through donations in exchange the fans would send high res images to LoveLove. These images would in turn be animated and the fans would appear in the music video. Not only was this a great way to fund the music video but it meant that the fans would directly engage with the music video. We also wanted the video to be interactive and we made three interactive endings where the fans could choose which animal to save.\nFurther to the video we created three Games that the fans could play on Gabby Young’s website driving traffic directly from the videos hosted on Youtube. \n\nThe Result \n\nThe video resulted in over 45,000 hits on YouTube alone and gained much press regarding the interactive elements including……./n“LoveLove are an amazing team to work with – not only did they deliver a video that far surpassed my expectations but they were professional, creative, full of original ideas and a joy to work with. I will happily work with them again and again!” – Gabby Young"
    videoEleven.id = "yOCf-UzU6gs"
    videos.append(videoEleven)
    
    let videoTwelve = Video()
    videoTwelve.title = "BOURNEMOUTH TOURISM COASTAL DRONE"
    videoTwelve.description = "The Brief \n\nAfter the highly successful Study English in the UK project, Bournemouth Tourism once again commissioned LoveLove Films to produce an aerial photography video that also tied in with the Britain is Great Campaign.\nBournemouth Tourism approached LoveLove Films with a desire for a video that was exclusively aerial footage, with the objective to showcase Bournemouth’s and Poole’s coastline as an area of extreme natural beauty. \n\nThe Process \n\nLoveLove Films rapidly organised a drone shoot for the project. We shot a video that ranged from the continuous stretch of beach from Hengistbury Head to Sandbanks. The video incorporates many different scenic bird’s eye view shots of the beach; from shots tracking along the beach to shots hovering along the Bournemouth and Boscombe piers.\nMotion graphic text stating the locations and encouraging messages were added into the scenes in post-production along with those for the Britain is Great campaign. Finally an epic and exciting audio track was added, giving the video an exhilarating feel. \n\nThe Result \n\nThe video was very successful online. On Facebook it received over 88,000 views, 1500 likes and 2500 shares as well as almost 200 appreciative comments within a week of being uploaded.\nThe Coastal Drone video is a brilliant example of using drone footage to show a place in a new light and to use a video to attract a large audience."
    videoTwelve.id = "YSjd-m-O1A0"
    videos.append(videoTwelve)
    
    
    let videoThirteen = Video()
    videoThirteen.title = "BOURNEMOUTH COUNCIL – BRITAIN IS GREAT"
    videoThirteen.description = "The Brief \n\nBournemouth Tourism commissioned LoveLove Films to create a video that would encourage central and southern American students to study English in Bournemouth and Poole. They wanted a video that would show off the positive elements of Bournemouth, but which would also be emotional and relatable. Additionally, they wanted a video that would fit in with the Britain is GREAT campaign. \n\nThe Process \n\nLoveLove Films came up with a concept and storyline for a character, who studies English as a foreign language in Bournemouth. It was decided to create a video with no dialogue so that it could be appreciated on a global level, with no language barrier. It was filmed in the early part of 2016 to a tight deadline, and involved filming multiple locations across Dorset. In the edit the Britain is GREAT branding was added to tie it into the larger campaign. \n\nThe Result \n\nThe video was uploaded to YouTube & Facebook and had a website built for it. The video managed to gain more than 100,000 views within a week of being uploaded over the different media platforms."
    videoThirteen.id = "xoGQ4_jsJng"
    videos.append(videoThirteen)
    
    let videoFourteen = Video()
    videoFourteen.title = "CISCO – CREATING GLOBAL PROBLEM SOLVERS"
    videoFourteen.description = "The Brief \n\nLoveLove Films was approached by American technology company Cisco, and asked to produce a visually engaging corporate animation that aimed to showcase the crucial work the company does in helping set up networks and connect people in various regions across the globe. \nThe video was to be used to convey a range of key projects that Cisco run throughout the world, including their NetHope disaster relief project that helped aid workers during the recent Ebola crisis in Africa, as well as their NetAcademy scheme which helps provide IT skills development and future job opportunities for those people who live in under-developed countries. \n\nThe Process \n\nWorking to a tight deadline with Cisco departments in both the UK and America, LoveLove Film’s animation team helped to not only build upon the initial concept, but worked to develop a unique animation style and striking character designs. Our team of animators then used some of the latest software to bring the Cisco story to life, putting the emphasis of the story on the variety of ways in which the power of technology is helping to change the world for the better. \n\nThe Result \n\nThe final video is a great example of how animation is a powerful tool when it comes to effective storytelling; the finished production was not only an engaging and stimulating video but one that conveyed Cisco’s core messages in innovative and unique way. Importantly, the end result achieved one of Cisco’s key aims in managing to successfully combine live-action stills with 2D animation.\nThe Rich Media Marketing team at Cisco we’re extremely impressed with the overall animation that we produced and distributed the video online via their own YouTube channel and their company website."
    videoFourteen.id = "NOrPe-1lgC8"
    videos.append(videoFourteen)
    
    let videoFifteen = Video()
    videoFifteen.title = "CREDITPLUS TV COMMERCIAL"
    videoFifteen.description = "The Brief \n\nLoveLove were approached by Creditplus to produce a TV Commercial. Creditplus desired a TV commercial that would be a friendly and open introduction to their car finance services. Through concept meetings with the client, it was decided that a fun style of animation would suit the brand and through ‘Benny’s Story’ showcase their service. \n\nThe Process \n\nLoveLove’s in-house writer worked on developing ‘Benny’s story’ with feedback and collaboration from the client. Following this, our in-house animation team began creating the assets and the animation process began! Alongside this LoveLove handled the Clearcast process on behalf of the client, resulting in a smooth transition from script and substantiation doc stage through to the upload of the final clocked cut of the commercial. \n\nThe Result \n\nLoveLove Films were extremely pleased with the end result and the TV advert for Credit Plus car finance will be aired in the following regions Southampton, Portsmouth, Brighton and Little Hampton covering the south coast! The TV advert has gone live at the beginning of July, across various Sky Channels.\nMark Humphrys, Head of Digital and Marketing at Creditplus can be quoted: ‘We hired the team at LoveLove Films to help us to produce a set of videos. We work in a complex industry but LoveLove did a fantastic job at planning out the project, working with us to get the right message, and then finally delivering a set of videos that we love and that help to simplify the products that we provide. Georgina led the project really well. She was able to ensure that we didn’t run behind schedule and most importantly delivered excellent results. If you are looking for a company to produce your videos for you I would highly recommend Georgina and the team at LoveLove Films!"
    videoFifteen.id = "wOHtcinQP_4"
    videos.append(videoFifteen)
    
    return videos
}